spring:
  datasource:
    url: jdbc:mysql://localhost:2306/mall-demo?useSSL=true&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 1234qweR
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        connection:
          release_mode: auto
logging:
  level:
    root: info